config/routes.rb
PersonalTracker::Application.routes.draw do
  resources :users do
    resources :poops
  end

  devise_for :users

  

end

app/models/poop.rb
class Poop < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :poops
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poops_controller.rb
class PoopsController < ApplicationController
  before_action :set_poop, only: [:show, :edit, :update, :destroy]
  before_action :get_user

  # GET /poops
  # GET /poops.json
  def index
    @poops = @user.poops
  end

  # GET /poops/1
  # GET /poops/1.json
  def show
  end

  # GET /poops/new
  def new
    @poop = Poop.new
  end

  # GET /poops/1/edit
  def edit
  end

  # POST /poops
  # POST /poops.json
  def create
    @poop = @user.poops.new(poop_params)

    respond_to do |format|
      if @poop.save
        format.html { redirect_to user_poops_path, notice: 'Poop was successfully created.' }
        format.json { render action: 'show', status: :created, location: @poop }
      else
        format.html { render action: 'new' }
        format.json { render json: @poop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poops/1
  # PATCH/PUT /poops/1.json
  def update
    respond_to do |format|
      if @poop.update(poop_params)
        format.html { redirect_to user_poops_path, notice: 'Poop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poops/1
  # DELETE /poops/1.json
  def destroy
    @poop.destroy
    respond_to do |format|
      format.html { redirect_to user_poops_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def get_user
      @user = current_user
    end

    def set_poop
      @poop = Poop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poop_params
      params.require(:poop).permit(:user_id, :consistency, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poops_helper.rb
module PoopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PersonalTracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/poops/_form.html.erb
<%= form_for([@user,@poop]) do |f| %>
  <% if @poop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poop.errors.count, "error") %> prohibited this poop from being saved:</h2>

      <ul>
      <% @poop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :consistency %><br>
    <%= f.number_field :consistency %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poops/edit.html.erb
<h1>Editing poop</h1>

<%= render 'form' %>

<%= link_to 'Show', @poop %> |
<%= link_to 'Back', user_poops_path %>

app/views/poops/index.html.erb
<h1>Listing poops</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Consistency</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @poops.each do |poop| %>
      <tr>
        <td><%= poop.user_id %></td>
        <td><%= poop.consistency %></td>
        <td><%= poop.notes %></td>
        <td><%= link_to 'Show', user_poop_path(@user,poop) %></td>
        <td><%= link_to 'Edit', edit_user_poop_path(@user,poop) %></td>
        <td><%= link_to 'Destroy', user_poop_path(@user,poop), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poop', new_user_poop_path %>

app/views/poops/new.html.erb
<h1>New poop</h1>

<%= render 'form' %>

<%= link_to 'Back', user_poops_path %>

app/views/poops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @poop.user_id %>
</p>

<p>
  <strong>Consistency:</strong>
  <%= @poop.consistency %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @poop.notes %>
</p>

<%= link_to 'Edit', edit_user_poop_path(@poop) %> |
<%= link_to 'Back', user_poops_path %>